services:
  app:
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      BMGT435_MYSQL_HOST: mysql
      BMGT435_MYSQL_USER: root
      BMGT435_MYSQL_PASSWORD: root
      BMGT435_MYSQL_DB: bmgt435-mysql
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bmgt435-mysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - bmgt435-mysql:/var/lib/mysql


volumes:
  bmgt435-mysql: