services:

  app:
    image: chaconn3/bmgt435_service
    restart: always
    ports:
      - 8000:8000
    environment:
      APP_FRONTEND_HOST: localhost:4173 # for local development CORS config
      APP_USE_MYSQL: 1
      APP_MYSQL_HOST: mysql
      APP_MYSQL_USER: root
      APP_MYSQL_PASSWORD: root
      APP_MYSQL_DB: bmgt435-mysql # name of the database
      APP_MYSQL_PORT: 3306
      APP_DEBUG: 1
    depends_on:
      - mysql
  
  mysql: # main db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bmgt435-mysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - bmgt435-mysql:/var/lib/mysql

volumes:
  bmgt435-mysql: