# Generated by Django 4.2.1 on 2023-11-17 23:28

import bmgt435_elp.bmgtModels
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMGTCase',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('visible', models.BooleanField(default=True)),
                ('max_submission', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTCaseConfig',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('config_json', bmgt435_elp.bmgtModels.BMGTJsonField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='BMGTCaseRecord',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=None, null=True)),
                ('state', models.IntegerField(default=0, verbose_name=[(0, 'Running'), (1, 'Success'), (2, 'Failed')])),
                ('summary_dict', models.TextField(default='')),
                ('file_name', models.CharField(editable=False, max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('content', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTGroup',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTSemester',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('season', models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BMGTUser',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('did', models.CharField(db_index=True, max_length=60, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('password', models.CharField(default='', max_length=100)),
                ('activated', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=5)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_elp.bmgtgroup')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_elp.bmgtsemester')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTTransaction',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='UNKNOWN', max_length=10)),
                ('path', models.CharField(default='', max_length=100)),
                ('status_code', models.IntegerField(default=0)),
                ('ip', models.CharField(default='', max_length=20)),
                ('device', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_elp.bmgtuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='bmgtsemester',
            constraint=models.UniqueConstraint(fields=('year', 'season'), name='unique_semester'),
        ),
        migrations.AddConstraint(
            model_name='bmgtsemester',
            constraint=models.CheckConstraint(check=models.Q(('year__gte', 2022)), name='year_constraint'),
        ),
        migrations.AddConstraint(
            model_name='bmgtsemester',
            constraint=models.CheckConstraint(check=models.Q(('season__in', ['spring', 'summer', 'fall'])), name='season_constraint'),
        ),
        migrations.AddField(
            model_name='bmgtgroup',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_elp.bmgtsemester'),
        ),
        migrations.AddField(
            model_name='bmgtfeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_elp.bmgtuser'),
        ),
        migrations.AddField(
            model_name='bmgtcaserecord',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_elp.bmgtcase'),
        ),
        migrations.AddField(
            model_name='bmgtcaserecord',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_elp.bmgtgroup'),
        ),
        migrations.AddField(
            model_name='bmgtcaserecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_elp.bmgtuser'),
        ),
        migrations.AddField(
            model_name='bmgtcaseconfig',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_elp.bmgtcase'),
        ),
        migrations.AddField(
            model_name='bmgtcaseconfig',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_elp.bmgtsemester'),
        ),
        migrations.AddConstraint(
            model_name='bmgtcaseconfig',
            constraint=models.UniqueConstraint(fields=('case_id', 'semester_id'), name='unique_case_config'),
        ),
    ]
