# Generated by Django 4.2.1 on 2023-11-27 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_elp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmgtcaseconfig',
            name='edited_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
