# Generated by Django 4.2.1 on 2023-09-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_elp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmgtfeedback',
            old_name='user_id',
            new_name='user',
        ),
    ]
