# Generated by Django 4.2.1 on 2023-10-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_elp', '0002_rename_user_id_bmgtfeedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmgtgroup',
            old_name='semeter',
            new_name='semester',
        ),
    ]
