# Generated by Django 4.2.1 on 2023-11-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_elp', '0003_bmgtsystemstatus_bmgtgroup_is_frozen_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bmgtcaseconfig',
            name='unique_case_config',
        ),
        migrations.RemoveField(
            model_name='bmgtcaseconfig',
            name='semester',
        ),
        migrations.AddConstraint(
            model_name='bmgtcaseconfig',
            constraint=models.UniqueConstraint(fields=('case_id',), name='unique_case_config'),
        ),
    ]
