# Generated by Django 4.2.1 on 2023-11-02 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_elp', '0003_rename_semeter_bmgtgroup_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMGTTransaction',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='UNKNOWN', max_length=10)),
                ('path', models.CharField(default='', max_length=100)),
                ('status_code', models.IntegerField(default=0)),
                ('ip', models.CharField(default='', max_length=20)),
                ('device', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_elp.bmgtuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
