# Generated by Django 4.2.1 on 2023-11-02 21:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_elp', '0004_bmgttransaction_delete_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMGTSession',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('sid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_elp.bmgtuser')),
            ],
        ),
    ]
