# Generated by Django 4.2.1 on 2023-11-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_elp', '0005_bmgtsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtuser',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bmgtuser',
            name='did',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
        migrations.DeleteModel(
            name='BMGTSession',
        ),
    ]
