# Generated by Django 4.2.1 on 2023-11-10 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_elp', '0006_alter_bmgtuser_activated_alter_bmgtuser_did_and_more copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtgroup',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_elp.bmgtsemester'),
        ),
    ]
