# Generated by Django 4.1.6 on 2023-08-18 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMGTCase',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('visible', models.IntegerField(default=1, verbose_name=[(0, 'False'), (1, 'True')])),
                ('max_submission', models.IntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTGroup',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTTag',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseConfig',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('config_json', models.TextField(default='')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_platform.bmgtcase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTUser',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('did', models.CharField(max_length=60, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('password', models.CharField(default='', max_length=100)),
                ('activated', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=5)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTTagged',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_platform.bmgttag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_platform.bmgtuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMGTCaseRecord',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=None, null=True)),
                ('state', models.IntegerField(default=0, verbose_name=[(0, 'Running'), (1, 'Success'), (2, 'Failed')])),
                ('summary_json', models.TextField()),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtcase')),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
