# Generated by Django 4.1.6 on 2023-08-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmgtcaserecord',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtuser'),
        ),
    ]
