# Generated by Django 4.1.6 on 2023-07-26 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtuser',
            name='tag_id',
        ),
        migrations.AlterField(
            model_name='bmgtgroup',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bmgtuser',
            name='user_first_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bmgtuser',
            name='user_last_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='case_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='case_record_detail_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_platform.tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt435_platform.bmgtuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
