# Generated by Django 4.1.6 on 2023-07-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0002_remove_bmgtuser_tag_id_alter_bmgtgroup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmgtgroup',
            name='flag_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bmgtuser',
            name='flag_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='flag_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caserecord',
            name='flag_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='flag_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='flag_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagged',
            name='flag_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
