# Generated by Django 4.1.6 on 2023-08-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0002_bmgtcaserecord_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtcaserecord',
            name='summary_json',
        ),
        migrations.AddField(
            model_name='bmgtcaserecord',
            name='summary_dict',
            field=models.TextField(default=''),
        ),
    ]
