# Generated by Django 4.1.6 on 2023-08-21 22:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0003_remove_bmgtcaserecord_summary_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMGTFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('content', models.TextField(default='')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
