# Generated by Django 4.1.6 on 2023-07-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0003_bmgtgroup_flag_deleted_bmgtuser_flag_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtgroup',
            name='flag_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bmgtuser',
            name='flag_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bmgtuser',
            name='user_activated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='flag_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='flag_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='flag_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='flag_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tagged',
            name='flag_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
