# Generated by Django 4.2.1 on 2023-09-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0004_bmgtfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BMGTFeedback',
        ),
    ]
