# Generated by Django 4.1.6 on 2023-07-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0004_alter_bmgtgroup_flag_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtuser',
            name='user_did',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
