# Generated by Django 4.1.6 on 2023-07-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0005_alter_bmgtuser_user_did'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmgtuser',
            old_name='user_activated',
            new_name='activated',
        ),
        migrations.RenameField(
            model_name='bmgtuser',
            old_name='user_did',
            new_name='did',
        ),
        migrations.RenameField(
            model_name='bmgtuser',
            old_name='user_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='bmgtuser',
            old_name='user_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='bmgtuser',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='caserecord',
            old_name='case_record_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='case_record_detail_json',
        ),
        migrations.RemoveField(
            model_name='caserecord',
            name='case_record_status',
        ),
        migrations.AddField(
            model_name='caserecord',
            name='detail_json',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bmgtgroup',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
