# Generated by Django 4.2.1 on 2023-09-06 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0005_delete_bmgtfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('sign-in', 'sign-in'), ('sign-up', 'sign-up'), ('sign-out', 'sign-out'), ('forget-password', 'forget-password'), ('submit-case', 'submit-case')], max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
