# Generated by Django 4.2.1 on 2023-09-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0007_bmgtfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgttagged',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='bmgttagged',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bmgtgroup',
            name='number',
            field=models.IntegerField(default=579496),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bmgtcase',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='BMGTTag',
        ),
        migrations.DeleteModel(
            name='BMGTTagged',
        ),
    ]
