# Generated by Django 4.2.1 on 2023-09-21 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0008_remove_bmgttagged_tag_id_remove_bmgttagged_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMGTSemester',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('season', models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
