# Generated by Django 4.2.1 on 2023-09-21 23:10

import bmgt435_platform.bmgtModels
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0009_bmgtsemester'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmgtgroup',
            name='semeter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtsemester'),
        ),
        migrations.AddField(
            model_name='bmgtuser',
            name='semester_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtsemester'),
        ),
        migrations.AlterField(
            model_name='bmgtsemester',
            name='year',
            field=models.IntegerField(validators=[bmgt435_platform.bmgtModels.BMGTSemester.semester_year_validator]),
        ),
        migrations.AlterUniqueTogether(
            name='bmgtsemester',
            unique_together={('year', 'season')},
        ),
    ]
