# Generated by Django 4.1.6 on 2023-07-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0009_alter_bmgtuser_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtuser',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
