# Generated by Django 4.1.6 on 2023-08-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0010_alter_bmgtuser_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtuser',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtgroup'),
        ),
        migrations.AlterField(
            model_name='bmgtuser',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.role'),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='case_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.case'),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtgroup'),
        ),
    ]
