# Generated by Django 4.2.1 on 2023-09-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0010_bmgtgroup_semeter_id_bmgtuser_semester_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmgtcaserecord',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='bmgtcaserecord',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='bmgtcaserecord',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bmgtgroup',
            old_name='semeter_id',
            new_name='semeter',
        ),
        migrations.RenameField(
            model_name='bmgtuser',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='bmgtuser',
            old_name='semester_id',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='caseconfig',
            old_name='case_id',
            new_name='case',
        ),
    ]
