# Generated by Django 4.1.6 on 2023-08-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0011_alter_bmgtuser_group_id_alter_bmgtuser_role_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtgroup',
            name='name',
        ),
    ]
