# Generated by Django 4.2.1 on 2023-09-22 00:18

import bmgt435_platform.bmgtModels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0011_rename_case_id_bmgtcaserecord_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmgtcaserecord',
            name='case_record_file_name',
            field=models.CharField(auto_created=True, default=bmgt435_platform.bmgtModels.BMGTCaseRecord.generate_file_name, editable=False, max_length=100),
        ),
    ]
