# Generated by Django 4.1.6 on 2023-08-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0012_remove_bmgtgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtuser',
            name='role_id',
        ),
        migrations.AddField(
            model_name='bmgtuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
