# Generated by Django 4.1.6 on 2023-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0013_remove_bmgtuser_role_id_bmgtuser_role_delete_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='BMGTCase',
        ),
        migrations.RenameModel(
            old_name='CaseRecord',
            new_name='BMGTCaseRecord',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='BMGTTag',
        ),
        migrations.RenameModel(
            old_name='Tagged',
            new_name='BMGTTagged',
        ),
        migrations.AlterField(
            model_name='bmgtuser',
            name='role',
            field=models.IntegerField(choices=[(111, 'Admin'), (2, 'User')], default=2),
        ),
    ]
