# Generated by Django 4.2.1 on 2023-09-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0013_alter_bmgtcaserecord_case_record_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtcaserecord',
            name='case_record_file_name',
        ),
        migrations.AddField(
            model_name='bmgtcaserecord',
            name='file_name',
            field=models.CharField(default='dsads', editable=False, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
