# Generated by Django 4.1.6 on 2023-08-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0014_rename_case_bmgtcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmgtcase',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bmgtcaserecord',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
