# Generated by Django 4.1.6 on 2023-08-10 01:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0015_bmgtcase_visible_alter_bmgtcaserecord_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtcase',
            name='description',
        ),
        migrations.AddField(
            model_name='bmgtcase',
            name='max_simulation',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='bmgtcase',
            name='max_submission',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='BMGTCaseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('flag_deleted', models.IntegerField(default=0)),
                ('config_json', models.TextField(default='')),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmgt435_platform.bmgtcase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
