# Generated by Django 4.1.6 on 2023-08-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0016_remove_bmgtcase_description_bmgtcase_max_simulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=5),
        ),
    ]
