# Generated by Django 4.1.6 on 2023-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0017_alter_bmgtuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtcase',
            name='visible',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bmgtuser',
            name='activated',
            field=models.IntegerField(default=0),
        ),
    ]
