# Generated by Django 4.1.6 on 2023-08-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0019_remove_bmgtcase_flag_deleted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BMGTCaseConfig',
        ),
    ]
