# Generated by Django 4.1.6 on 2023-08-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0021_bmgtcaserecord_success_alter_bmgtcase_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtcaserecord',
            name='success',
        ),
        migrations.AddField(
            model_name='bmgtcaserecord',
            name='state',
            field=models.IntegerField(default=0, verbose_name=[(0, 'Running'), (1, 'Success'), (2, 'Failed')]),
        ),
    ]
