# Generated by Django 4.1.6 on 2023-08-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0022_remove_bmgtcaserecord_success_bmgtcaserecord_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtcaserecord',
            name='score',
            field=models.FloatField(default=None, null=True),
        ),
    ]
