# Generated by Django 4.1.6 on 2023-08-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0023_alter_bmgtcaserecord_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtcase',
            name='max_simulation',
        ),
    ]
