# Generated by Django 4.1.6 on 2023-08-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt435_platform', '0024_remove_bmgtcase_max_simulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtcaserecord',
            name='detail_json',
        ),
    ]
