# Generated by Django 4.1.6 on 2023-07-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=50)),
                ('case_create_time', models.DateTimeField()),
                ('case_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='user', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_did', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=70)),
                ('user_password', models.CharField(max_length=50)),
                ('user_create_time', models.DateTimeField()),
                ('user_activated', models.BooleanField(default=False)),
                ('user_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.role')),
                ('user_tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='', max_length=10)),
                ('group_create_time', models.DateTimeField()),
                ('group_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.user')),
            ],
        ),
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('case_record_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('case_record_create_time', models.DateTimeField()),
                ('case_record_status', models.IntegerField(default=0)),
                ('case_record_score', models.FloatField(default=0.0)),
                ('case_record_detail_json', models.TextField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.case')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.group')),
            ],
        ),
    ]
