# Generated by Django 4.1.6 on 2023-07-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
