# Generated by Django 4.1.6 on 2023-07-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt_platform', '0002_alter_group_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_did',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=60),
        ),
    ]
