# Generated by Django 4.1.6 on 2023-07-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt_platform', '0003_alter_user_user_did_alter_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_first_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_last_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
