# Generated by Django 4.1.6 on 2023-07-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt_platform', '0004_remove_user_user_name_user_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='case_record_detail_json',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.tag'),
        ),
    ]
