# Generated by Django 4.1.6 on 2023-07-19 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt_platform', '0005_alter_case_case_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMGTUser',
            fields=[
                ('user_did', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=60, null=True)),
                ('user_last_name', models.CharField(max_length=60, null=True)),
                ('user_email', models.EmailField(max_length=70, null=True)),
                ('user_password', models.CharField(max_length=50)),
                ('user_create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_owner_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='bmgtuser',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.group'),
        ),
        migrations.AddField(
            model_name='bmgtuser',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.role'),
        ),
        migrations.AddField(
            model_name='bmgtuser',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmgt_platform.tag'),
        ),
    ]
