# Generated by Django 4.1.6 on 2023-07-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt_platform', '0006_bmgtuser_remove_group_group_owner_id_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtuser',
            name='user_password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
