# Generated by Django 4.1.6 on 2023-07-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt_platform', '0007_alter_bmgtuser_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmgtuser',
            name='user_email',
        ),
    ]
