# Generated by Django 4.1.6 on 2023-07-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmgt_platform', '0008_remove_bmgtuser_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmgtuser',
            name='user_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
